config/routes.rb
Rails.application.routes.draw do
  root "feed#show"

  get "sign_up", to: "users#new"
  post "sign_up", to: "users#create"

  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"

  resource :profile, only: [ :edit, :update ], controller: "users"
  namespace :users do
    patch "change_password", to: "passwords#update"
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/app_session.rb
class AppSession < ApplicationRecord
  belongs_to :user

  has_secure_password :token, validations: false

  before_create do
    self.token = self.class.generate_unique_secure_token
  end

  def to_h
    {
      user_id: user.id,
      app_session_id: self.id,
      token: self.token
    }
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :user, :app_session, :organization
end

app/models/membership.rb
class Membership < ApplicationRecord
  belongs_to :user
  belongs_to :organization
end

app/models/organization.rb
class Organization < ApplicationRecord
  has_many :memberships, dependent: :destroy
  has_many :members, through: :memberships, source: :user
end

app/models/user.rb
class User < ApplicationRecord
  include Authentication

  validates :name, presence: true
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }, uniqueness: { case_sensitive: false }

  has_many :membershios, dependent: :destroy
  has_many :organizations, through: :memberships

  before_validation :strip_extraneous_spaces

  private

    def strip_extraneous_spaces
      self.name = self.name&.strip
      self.email = self.email&.strip
    end
end

app/models/user/authentication.rb
module User::Authentication
  extend ActiveSupport::Concern

  included do
    validates :password,
      on: [ :create, :password_change ],
      presence: true,
      length: { minimum: 8 }

    has_secure_password
    has_many :app_sessions
  end

  class_methods do
    def create_app_session(email:, password:)
      return nil unless user = User.find_by(email: email&.downcase)

      user.app_sessions.create if user.authenticate(password)
    end
  end

  def authenticate_app_session(app_session_id:, app_session_token:)
    app_sessions.find(app_session_id).authenticate_token(app_session_token)
  rescue ActiveRecord::RecordNotFound
    nil
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Authenticate

  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  helper_method :turbo_frame_request?
  helper_method :turbo_native_app?
end

app/controllers/concerns/authenticate.rb
module Authenticate
  extend ActiveSupport::Concern

  included do
    before_action :authenticate
    before_action :require_login, unless: :logged_in?

    helper_method :logged_in?
    helper_method :current_user
  end

  class_methods do
    def skip_authentication(**options)
      skip_before_action :authenticate, options
      skip_before_action :require_login, options
    end

    def allow_unauthenticated(**options)
      skip_before_action :require_login, options
    end
  end

  protected

    def log_in(app_session)
      cookies.encrypted.permanent[:app_session] = {
        value: app_session.to_h
      }
    end

    def logged_in?
      current_user.present?
    end

    def log_out
      Current.app_session&.destroy
      cookies.delete(:app_session)
    end

    def current_user
      Current.user
    end

  private

    def authenticate
      Current.app_session = authenticate_using_cookie
      Current.user = Current.app_session&.user
    end

    def authenticate_using_cookie
      app_session = cookies.encrypted[:app_session]
      authenticate_using app_session&.with_indifferent_access
    end

    def authenticate_using(data)
      data => { app_session_id:, user_id:, token: }

      user = User.find(user_id)
      user.authenticate_app_session(
        app_session_id: app_session_id,
        app_session_token: token
      )

    rescue NoMatchingPatternError, ActiveRecord::RecordNotFound
      nil
    end

    def require_login
      flash.now[:notice] = t("login_required")
      render "sessions/new", status: :unauthorized
    end
end

app/controllers/feed_controller.rb
class FeedController < ApplicationController
  allow_unauthenticated

  def show
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_authentication only: [ :new, :create ]

  def new
  end

  def create
    @app_session = User.create_app_session(
      email: login_params[:email],
      password: login_params[:password]
    )

    if @app_session
      log_in(@app_session)

      flash[:success] = t(".success")
      return recede_or_redirect_to root_path, status: :see_other
    end

    flash.now[:danger] = t(".incorrect_details")
    render :new, status: :unprocessable_entity
  end

  def destroy
    log_out

    redirect_to root_path,
      status: :see_other,
      flash: { success: t(".success") }
  end

  private

  def login_params
    @login_params ||=
      params.require(:user).permit(:email, :password)
  end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < ApplicationController
  before_action :authenticate_current_password

  def update
    @user.password = params.dig(:user, :password)

    if @user.save(context: :password_change)
      return redirect_to edit_profile_path, status: :see_other, flash: { success: t(".success") }
    end

    render "users/edit", status: :unprocessable_entity
  end

  private
    def authenticate_current_password
      @user = current_user
      current_password = params.dig(:user, :current_password)

      unless @user.authenticate(current_password)
        flash.now[:danger] = t(".incorrect_password")
        render "users/edit", status: :unprocessable_entity
      end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_authentication only: [ :new, :create ]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      @organization = Organization.create(members: [ @user ])
      @app_session = @user.app_sessions.create
      log_in(@app_session)

      flash[:success] = t(".welcome", name: @user.name)
      return recede_or_redirect_to root_path, status: :see_other
    end

    render :new, status: :unprocessable_entity
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user

    if @user.update(update_params)
      return redirect_to edit_profile_path,
        status: :see_other,
        flash: { success: t(".success") }
    end

    render :edit, status: :unprocessable_entity
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password)
    end

    def update_params
      params.require(:user).permit(:name, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title
    return t("piazza") unless content_for?(:title)
    return content_for(:title) if turbo_native_app?

    "#{content_for(:title)} | #{t("piazza")}"
  end
end

app/helpers/feed_helper.rb
module FeedHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users/passwords_helper.rb
module Users::PasswordsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/feed/show.html.erb
<h1>Feed#show</h1>
<p>Find me in app/views/feed/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="theme-light">
  <head>
    <title><%= title %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body>
    <%= render "shared/navbar" unless turbo_native_app? %>
    <%= render "shared/flashes"%>
    <main>
      <%= yield %>
    </main>
  </body>
</html>

app/views/shared/_flashes.html.erb
<div class="container is-fluid" data-turbo-cache="false">
  <% flash.each do |level, message| %>
    <%= tag.div class: "notification is-#{level} is-light has-text-centered mt-4" do %>
      <%= message %>
    <% end %>
  <% end %>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar has-background-link-light" role="navigation" aria-label="main navigation" data-controller="navbar">
  <div class="navbar-brand">
    <%= link_to root_path, class: "navbar-item" do %>
      <strong class="is-size-3">Piazza</strong>
    <% end %>
    <a role="button"
      class="navbar-burger"
      aria-label="menu"
      aria-expanded="false"
      data-navbar-target="burger"
      data-action="navbar#toggle">
      <span></span>
      <span></span>
      <span></span>
      <span></span>
    </a>
  </div>

  <div class="navbar-menu" data-navbar-target="menu">
    <div class="navbar-start">
      <%= link_to t(".create_ad"), "#", class: "navbar-item" %>
      <%= link_to t(".messages"), "#", class: "navbar-item" if logged_in? %>
    </div>

    <div class="navbar-end">
      <% if logged_in? %>

        <%= tag.div class: "navbar-item has-dropdown is-hoverable mr-4" do %>
          <%= link_to current_user.name, edit_profile_path, id: "current_user_name", class: "navbar-link" %>
          <div class="navbar-dropdown is-right">
            <%= link_to t(".profile"), edit_profile_path, class: "navbar-item" %>
            <%= link_to t(".my_ads"), "#", class: "navbar-item" %>
            <%= link_to t(".saved_ads"), "#", class: "navbar-item" %>
            <hr class="navbar-divider">
            <%= link_to t(".logout"), logout_path, class: "navbar-item", data: { turbo_method: :delete } %>
          </div>
        <% end %>

      <% else %>

        <%= tag.div class: "navbar-item" do %>
          <div class="buttons">
            <%= link_to t(".sign_up"), sign_up_path, class: "button is-primary" %>
            <%= link_to t(".login"), login_path, class: "button is-light" %>
          </div>
        <% end %>

      <% end %>
    </div>
  </div>

</nav>

app/views/users/edit.html.erb
<% content_for :title, current_user.name %>

<%= turbo_frame_tag :user_details do %>
  <layout-columns class="columns is-centered">
    <layout-column class="column box is-5 mt-6 p-5 m-4">
      <h1 class="title has-text-centered">
        <%= t(".your_details") %>
      </h1>
      <%=
        form_with(
          model: @user,
          url: profile_path,
          class: "is-flex is-flex-direction-column"
        ) do |form|
      %>
        <%= render "shared/flashes" if turbo_frame_request? %>
        <div class="block">
          <%= form.label :name, class: "label" %>
          <%= form.text_field :name, class: "input" %>
        </div>
        <div class="block">
          <%= form.label :email, class: "label" %>
          <%= form.email_field :email, class: "input" %>
        </div>

        <%=
          form.submit t(".save_profile"),
            class: "button is-primary is-align-self-flex-end mb-3 mt-3"
        %>
      <% end %>
    </layout-column>
  </layout-columns>
  <%= turbo_stream.update :current_user_name do %>
    <%= current_user.name %>
  <% end %>
<% end %>

<%= turbo_frame_tag :change_password do %>
  <layout-columns class="columns is-centered">
    <layout-column class="column box is-5 mt-6 p-5 m-4">
      <h1 class="title has-text-centered">
        <%= t(".change_password") %>
      </h1>
      <%=
        form_with(
          model: @user,
          url: users_change_password_path,
          class: "is-flex is-flex-direction-column"
        ) do |form|
      %>
        <%= render "shared/flashes" if turbo_frame_request? %>
        <div class="block">
          <%= form.label :current_password, class: "label" %>
          <%= form.password_field :current_password, class: "input" %>
        </div>
        <div class="block">
          <%= form.label :password, value: t(".new_password"), class: "label" %>
          <%= form.password_field :password, class: "input" %>
        </div>
        <%=
          form.submit t(".change_password_button"),
            class: "button is-primary is-align-self-flex-end mb-3 mt-3"
        %>
      <% end %>
    </layout-column>
  </layout-columns>
<% end %>

app/views/users/new.html.erb
<% content_for :title, t(".title") %>

<layout-columns class="columns is-centered">
  <layout-column class="column box is-5 mt-6 p-5 m-4">
    <h1 class="title has-text-centered">
      <%= t(".title") %>
    </h1>

    <%=
      form_with(
        model: @user,
        url: sign_up_path,
        class: "is-flex is-flex-direction-column"
      ) do |form| %>
      <div class="block">
        <%= form.label :name, class: "label" %>
        <%= form.text_field :name, class: "input" %>
      </div>

      <div class="block">
        <%= form.label :email, class: "label" %>
        <%= form.email_field :email, class: "input" %>
      </div>

      <div class="block">
        <%= form.label :password, class: "label" %>
        <%= form.password_field :password, class: "input" %>
      </div>

      <%=
        form.submit t(".sign_up"), class: "button is-primary is-large is-align-self-flex-end mb-3 mt-3"
      %>
    <% end %>

    <%= tag.p class: "has-text-centered" do %>
      <%= t(".login_message") %>
      <%= link_to t(".login"), login_path %>
    <% end if turbo_native_app? %>
  </layout-column>
</layout-columns>